# For more info on HTTP files go to https://aka.ms/vs/httpfile

@Api_HostAddress = https://localhost:7253


GET {{Api_HostAddress}}/player

###


GET {{Api_HostAddress}}/player/66c09eb643c8298d2ef17c4e